spring.application.name=rendszer-service
spring.config.import=optional:configserver:http://localhost:8181
springdoc.swagger-ui.path=/swagger-ui-custom.html
spring.datasource.url=jdbc:postgresql://192.168.0.61:5432/koszegig
spring.datasource.username=webuser
spring.datasource.password=psoestrg
spring.datasource.driver-class-name=org.postgresql.Driver
//
spring.jpa.show-sql=true