spring.application.name=rendszer-service
spring.config.import=optional:configserver:http://localhost:8181
springdoc.swagger-ui.path=/swagger-ui-custom.html
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
//
spring.jpa.show-sql=true